### PR TITLE
add getLatLngs method

### PR DESCRIPTION
**Pull request by qpincon**
Following the same logic as setLatLngs(`pathData[]`), added `getLatLngs` to get the array of commands to draw the curve.

### CODE REVIEW

**Review by elfalem — APPROVED** [review]

**Comment by elfalem** [comment]
Thank you!

**Comment by qpincon** [comment]
No problem! It would be great if you could publish a new version, since the goal is to use this new function into Leaflet-geoman to draw curves. Thank you!

**Comment by elfalem** [comment]
:+1: Just published v0.9.0.

I had to modify the method to be a proper function. Otherwise it was returning `undefined`.

**Comment by qpincon** [comment]
Perfect, sorry about that.

**Pull request merged**
